FLASK_APP=microblog.py
FLASK_DEBUG=1
MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_USE_TLS=1
MAIL_USERNAME=fidel.ehirim1@gmail.com
MAIL_PASSWORD=gpin irrr hkoe lxwb
MS_TRANSLATOR_KEY=FD5tGYOar0GJk374LSAdUZD1TuEPVo0rB6zkdpSXp2y0AxJN2DoaJQQJ99BLAClhwhEXJ3w3AAAbACOGGudj
MS_TRANSLATOR_REGION=ukwest
ELASTICSEARCH_URL=https://localhost:9200
ELASTICSEARCH_USER=elastic
ELASTICSEARCH_PASSWORD=Dmm7jzIRqI_GuG6Iy+iW
ELASTICSEARCH_CA_CERT=C:\Users\User\OneDrive\Documents\elasticsearch-9.2.3-windows-x86_64\elasticsearch-9.2.3\config\certs\http_ca.crt