from flask import render_template, current_app
from flask_babel import _
from app.email import send_email




def send_password_reset_email(user):
    token = user.get_reset_password_token()
    #token generated by the user method

    #calls the helper function send_email that sends the email asynchronously.
    send_email(
        _('[Microblog] Reset Your Password'),
        sender=current_app.config['ADMINS'][0]
        #uses the first email from admins as the sender 
        ,recipients=[user.email]
        #sends the email to the users email 
        ,text_body=render_template('email/reset_password.txt',
                                         user=user, token=token),
        #render the text version of the email from the template
        html_body=render_template('email/reset_password.html',
                                       user=user, token=token)
        #render the html version of the email from the template
    )